# basic options
title: Steve's Blog
author: Steve
email: your-email@domain.com
description: Steve's Blog
twitter_username: jekyllrb
github_username:  steve4010

# Build settings
markdown: kramdown
theme: architect


permalink: /blog/:year/:month/:day/:title
